"""Pure-Python contracts for future Windows-native observation collection."""

from .api import (
    WindowsApiProtocol,
    WindowsFirewallApiProtocol,
    WindowsFirewallRulesApiProtocol,
    WindowsNetworkApiProtocol,
    WindowsSystemApiProtocol,
)
from .api_native import NativeWindowsApi
from .adapter import WindowsPlatformAdapter
from .buffer import NativeBufferRead, read_bounded_native_table
from .errors import (
    WindowsEndpointTable,
    WindowsEndpointTableDiagnostic,
    WindowsEndpointTableResultCode,
    WindowsEndpointValidationReason,
    WindowsFailureCode,
)
from .fake import FakeWindowsApi, WindowsApiFixture
from .system import collect_windows_system
from .network import collect_windows_network
from .firewall import (
    collect_windows_firewall_inbound_policy,
    collect_windows_firewall_technology,
)
from .firewall_rule_models import (
    RawWindowsApplicationPath,
    RawWindowsFirewallRule,
    RawWindowsInterfaceIdentity,
    WindowsFirewallPolicyView,
    WindowsFirewallRuleCollectionResult,
    WindowsFirewallRuleResultCode,
    WindowsRawFirewallInterfaceType,
    WindowsRawFirewallRuleAction,
    WindowsRawFirewallRuleDirection,
    WindowsRawFirewallUnsupportedFeature,
)
from .firewall_com_contracts import (
    APPROVED_FIREWALL_PROPERTY_GETTERS,
    APPROVED_PROPERTY_GETTER_COUNT,
    MAX_PROPERTY_GETTERS_PER_RULE,
    RESERVED_PROPERTY_GETTER_CAPACITY,
    WINDOWS_FIREWALL_COM_INIT_FLAGS,
    WINDOWS_FIREWALL_COM_METHODS,
    WindowsComCleanupStack,
    WindowsComContractError,
    WindowsComFailureCategory,
    WindowsComInitializationLease,
    WindowsComInitializationResult,
    WindowsComMethodKind,
    WindowsComOperationAccounting,
    WindowsComResourceKind,
    WindowsFirewallPropertyGetter,
    WindowsFirewallRuleInterfacePlan,
    WindowsOwnedBstr,
    WindowsOwnedVariant,
    WindowsSafeArrayElementType,
    WindowsSafeArrayValue,
    WindowsVariantType,
)
from .firewall_rules import (
    WINDOWS_FIREWALL_COM_ENUMERATION_CONTRACT,
    WindowsComGetterDeadlineGuarantee,
    WindowsComOwnershipRequirement,
    WindowsFirewallComEnumerationContract,
    WindowsFirewallRuleNormalizationResult,
    normalize_windows_firewall_rules,
    windows_application_identity,
)
from .firewall_rule_reader import (
    WindowsComInterfaceAvailability,
    WindowsFirewallRule2Query,
    WindowsFirewallRule2ReaderProtocol,
    WindowsFirewallRule3Query,
    WindowsFirewallRule3ReaderProtocol,
    WindowsFirewallRuleReaderProtocol,
    WindowsFirewallSingleRuleReadResult,
    read_windows_firewall_rule,
)
from .models import (
    RawFirewallProfile,
    RawMachineIdentity,
    RawProcessInfo,
    RawServiceInfo,
    RawTcpEndpoint,
    RawUdpEndpoint,
    RawWindowsSystemInfo,
    WindowsAddressFamily,
    WindowsApiResult,
    WindowsFirewallAction,
    WindowsFirewallEnablement,
    WindowsFirewallProfile,
    WindowsProfileState,
    WindowsServiceState,
    WindowsTcpState,
)

__all__ = [
    "FakeWindowsApi",
    "NativeBufferRead",
    "NativeWindowsApi",
    "RawFirewallProfile",
    "RawMachineIdentity",
    "RawProcessInfo",
    "RawServiceInfo",
    "RawTcpEndpoint",
    "RawUdpEndpoint",
    "RawWindowsSystemInfo",
    "RawWindowsApplicationPath",
    "RawWindowsFirewallRule",
    "RawWindowsInterfaceIdentity",
    "APPROVED_FIREWALL_PROPERTY_GETTERS",
    "APPROVED_PROPERTY_GETTER_COUNT",
    "MAX_PROPERTY_GETTERS_PER_RULE",
    "RESERVED_PROPERTY_GETTER_CAPACITY",
    "WINDOWS_FIREWALL_COM_INIT_FLAGS",
    "WINDOWS_FIREWALL_COM_METHODS",
    "WindowsAddressFamily",
    "WindowsApiFixture",
    "WindowsApiProtocol",
    "WindowsNetworkApiProtocol",
    "WindowsPlatformAdapter",
    "WindowsApiResult",
    "WindowsFailureCode",
    "WindowsEndpointTable",
    "WindowsEndpointTableDiagnostic",
    "WindowsEndpointTableResultCode",
    "WindowsEndpointValidationReason",
    "WindowsFirewallApiProtocol",
    "WindowsFirewallRulesApiProtocol",
    "WindowsFirewallAction",
    "WindowsFirewallEnablement",
    "WindowsFirewallProfile",
    "WindowsProfileState",
    "WindowsFirewallPolicyView",
    "WindowsFirewallRuleCollectionResult",
    "WindowsFirewallRuleResultCode",
    "WindowsRawFirewallInterfaceType",
    "WindowsRawFirewallRuleAction",
    "WindowsRawFirewallRuleDirection",
    "WindowsRawFirewallUnsupportedFeature",
    "WINDOWS_FIREWALL_COM_ENUMERATION_CONTRACT",
    "WindowsComGetterDeadlineGuarantee",
    "WindowsComCleanupStack",
    "WindowsComContractError",
    "WindowsComFailureCategory",
    "WindowsComInitializationLease",
    "WindowsComInitializationResult",
    "WindowsComMethodKind",
    "WindowsComOperationAccounting",
    "WindowsComResourceKind",
    "WindowsComOwnershipRequirement",
    "WindowsFirewallComEnumerationContract",
    "WindowsFirewallRuleNormalizationResult",
    "WindowsComInterfaceAvailability",
    "WindowsFirewallRule2Query",
    "WindowsFirewallRule2ReaderProtocol",
    "WindowsFirewallRule3Query",
    "WindowsFirewallRule3ReaderProtocol",
    "WindowsFirewallRuleReaderProtocol",
    "WindowsFirewallSingleRuleReadResult",
    "WindowsFirewallPropertyGetter",
    "WindowsFirewallRuleInterfacePlan",
    "WindowsOwnedBstr",
    "WindowsOwnedVariant",
    "WindowsSafeArrayElementType",
    "WindowsSafeArrayValue",
    "WindowsVariantType",
    "WindowsServiceState",
    "WindowsSystemApiProtocol",
    "WindowsTcpState",
    "collect_windows_system",
    "collect_windows_network",
    "collect_windows_firewall_inbound_policy",
    "collect_windows_firewall_technology",
    "normalize_windows_firewall_rules",
    "read_windows_firewall_rule",
    "windows_application_identity",
    "read_bounded_native_table",
]
